---
- name: Prepare (uv upgrade)
  hosts: all
  become: true

  pre_tasks:
    - name: Set uv variables for old version installation
      set_fact:
        miarecweb_install_uv: true
        uv_version: "{{ lookup('env', 'UV_OLD_VERSION') }}"
        uv_install_dir: "{{ lookup('env', 'UV_INSTALL_DIR') }}"
        uv_download_base_url: "https://github.com/astral-sh/uv/releases/download"
        uv_verify_checksum: true

  roles:
    - role: ansible-role-miarecweb
      tags:
        - miarecweb
