---
- name: Prepare (uv upgrade)
  hosts: all
  become: true

  vars:
    uv_download_base_url: "https://github.com/astral-sh/uv/releases/download"

  tasks:
    - block:
        - name: Set uv variables from environment
          set_fact:
            uv_old_version: "{{ lookup('env', 'UV_OLD_VERSION') }}"
            uv_install_dir: "{{ lookup('env', 'UV_INSTALL_DIR') }}"

        - name: Determine architecture
          set_fact:
            _uv_architecture: >-
              {%- set arch = ansible_facts['architecture'] | default('') -%}
              {%- if arch in ['x86_64', 'amd64'] -%}
              x86_64-unknown-linux-gnu
              {%- elif arch in ['aarch64', 'arm64'] -%}
              aarch64-unknown-linux-gnu
              {%- else -%}
              unsupported
              {%- endif -%}

        - name: Fail on unsupported architecture
          fail:
            msg: "Unsupported architecture for uv upgrade scenario: {{ ansible_facts['architecture'] }}"
          when: _uv_architecture == 'unsupported'

        - name: Ensure uv install directory exists
          file:
            path: "{{ uv_install_dir }}"
            state: directory
            mode: "0755"

        - name: Create temporary directory
          tempfile:
            state: directory
            prefix: uv-upgrade-
          register: _uv_tmp_dir

        - name: Download uv archive (old version)
          get_url:
            url: "{{ uv_download_base_url }}/{{ uv_old_version }}/uv-{{ _uv_architecture }}.tar.gz"
            dest: "{{ _uv_tmp_dir.path }}/uv.tar.gz"
            mode: "0644"

        - name: Extract archive (old version)
          unarchive:
            src: "{{ _uv_tmp_dir.path }}/uv.tar.gz"
            dest: "{{ _uv_tmp_dir.path }}"
            remote_src: true

        - name: Install old uv
          copy:
            src: "{{ _uv_tmp_dir.path }}/uv-{{ _uv_architecture }}/uv"
            dest: "{{ uv_install_dir }}/uv"
            owner: root
            group: root
            mode: "0755"
            remote_src: true

        - name: Install old uvx
          copy:
            src: "{{ _uv_tmp_dir.path }}/uv-{{ _uv_architecture }}/uvx"
            dest: "{{ uv_install_dir }}/uvx"
            owner: root
            group: root
            mode: "0755"
            remote_src: true

      always:
        - name: Clean up temporary directory
          file:
            path: "{{ _uv_tmp_dir.path | default('') }}"
            state: absent
          when: _uv_tmp_dir is defined and (_uv_tmp_dir.path | default('') | length > 0)
