---
dependency:
  name: galaxy
  options:
    requirements-file: ../default/collections.yml
driver:
  name: docker
platforms:
  - name: miarecweb-tls-${MOLECULE_DISTRO:-ubuntu2404}
    image: ghcr.io/miarec/${MOLECULE_DISTRO:-ubuntu2404}-systemd:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  env:
    ANSIBLE_VERBOSITY: ${MOLECULE_ANSIBLE_VERBOSITY:-0}
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/../
    MIARECWEB_VERSION: ${MOLECULE_MIARECWEB_VERSION:-"2025.12.2.15"}
    MIARECWEB_SECRET: ${MOLECULE_MIARECWEB_SECRET:-"secret"}
    PYTHON_VERSION: ${MOLECULE_PYTHON_VERSION:-"3.12"}

verifier:
  name: testinfra
  options:
    s: true
    verbose: true

scenario:
  name: tls
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - verify
    - destroy
