---
# Install and configure Apache
- name: Apache | Install and Configure Apache | Debian
  when: ansible_os_family == "Debian"
  block:
    - name: Apache | Install Apache package | Debian
      apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      with_items:
        - apache2

    - name: Apache | Enable a2enmod rewrite module | Debian
      shell: "a2enmod rewrite"

    - name: Apache | Restart Apache service | Debian
      service:
        name: apache2
        state: restarted
        enabled: true

- name: Apache | Install and Configure Apache | RedHat
  when:
    - ansible_os_family == "RedHat"
  block:

    # CentOS repository and UBI repository have mismatched versions of httpd
    # this causes and issue with httpd-devel is installed from CentOS repository
    # disabling UBI repository to force install from CentOS repository
    - name: Disable ubi-7 repository | RHEL 7
      command: yum-config-manager --disable ubi-7
      changed_when: false
      when: ansible_distribution_major_version == "7"

    # Install apache on CentOS7, Rocky8-9, RHEL8-9
    - name: Apache | Install Apache | RedHat
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - httpd
        - httpd-devel
        - mod_ssl

    # Configure Apache
    - name: Apache | Ensure httpd certs are installed | RHEL 8+
      command: /usr/libexec/httpd-ssl-gencerts
      when:
        - ansible_distribution_major_version | int >= 8

    - name: Apache | Restart and Enable Apache service | RedHat
      service:
        name: httpd
        state: started
        enabled: true


