---
# Install and configure Apache
- name: Debian - Install and Configure Apache
  block:
    - name: Debian - Install Apache package
      apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      with_items:
        - apache2

    - name: Debian - Enable a2enmod rewrite module
      shell: "a2enmod rewrite"

    - name: Debian - Restart Apache service
      service:
        name: apache2
        state: restarted
        enabled: true
  when: ansible_os_family == "Debian"


- name: CentOS 7 - Install and Configure Apache
  block:
    - name: CentOS 7 - Install Apache
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - httpd

    - name: Restart and Enable Apache service
      service:
        name: httpd
        state: started
        enabled: true

  when: ansible_distribution == "CentOS"
