---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Install prerequisites
      block:
        - name: Update apt cache
          apt:
            update_cache: true
            cache_valid_time: 600
          changed_when: false
          when: ansible_os_family == "Debian"

        # required for miarecweb.yml - Install dependencies (requirements.txt)
        - name: Install python-pip
          package:
            name: python-pip
            state: present

    - set_fact:
        miarecweb_version: "{{ lookup('env', 'MIARECWEB_VERSION') }}"
        miarecweb_secret: "{{ lookup('env', 'MIARECWEB_SECRET') }}"
        python_version: "{{ lookup('env', 'MIARECWEB_PYTHON_VERSION') }}"

  roles:
    - role: ansible-role-miarecweb
      tags:
        - miarecweb
