---
- name: Converge
  hosts: all
  become: true

  pre_tasks:

    - set_fact:
        miarecweb_version: "{{ lookup('env', 'MIARECWEB_VERSION') }}"
        miarecweb_secret: "{{ lookup('env', 'MIARECWEB_SECRET') }}"
        python_version: "{{ lookup('env', 'MIARECWEB_PYTHON_VERSION') }}"


    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 600
      changed_when: false
      when: ansible_os_family == "Debian"

    # required for miarecweb.yml - Install dependencies (requirements.txt)
    - name: Install python-pip
      package:
        name: python-pip
        state: present
      when: ansible_distribution == "CentOS"




    - name: Install dependencies from CentOS Repositories | RHEL 8+
      when:
        - ansible_distribution == "RedHat"
        - ansible_distribution_major_version >= "8"
      block:

      - name: Define repos and packages for RHEL 8
        set_fact:
          _tmp_repos:
            - name: powertools
              url: http://mirror.centos.org/centos/8-stream/PowerTools/x86_64/os/
              gpg: http://mirror.centos.org/centos/RPM-GPG-KEY-CentOS-Official

          _tmp_packages:
            - name: perl-IPC-Run
              repo: powertools
        when: ansible_distribution_major_version == "8"


      - name: Define repos and packages for RHEL 9
        set_fact:
          _tmp_repos:
            - name: crb
              url: https://mirror.stream.centos.org/9-stream/CRB/x86_64/os/
              gpg: http://mirror.centos.org/centos/RPM-GPG-KEY-CentOS-Official

          _tmp_packages:
            - name: unixODBC-devel
              repo: crb
            - name: perl-IPC-Run
              repo: crb

        when: ansible_distribution_major_version == "9"


      - name: Add Temporary Repositories | RHEL 8+
        yum_repository:
            name: "{{ item.name }}"
            description: "Centos {{ ansible_distribution_major_version }} - {{ item.name }}"
            baseurl: "{{ item.url }}"
            gpgkey: "{{ item.gpg }}"
            enabled: false
        with_items: "{{ _tmp_repos }}"
        loop_control:
          label: "{{ item.name }}"


      - name: Install missing packages | RHEL 8+
        yum:
          name: "{{ item.name }}"
          state: present
          enablerepo: "{{ item.repo }}"
          disable_gpg_check: true
        with_items: "{{ _tmp_packages }}"
        loop_control:
          label: "{{ item.name }}"

  roles:
    - role: ansible-role-miarecweb
      tags:
        - miarecweb
