---
- name: Converge
  hosts: all
  become: true

  pre_tasks:

    - set_fact:
        miarecweb_version: "{{ lookup('env', 'MIARECWEB_VERSION') }}"
        miarecweb_secret: "{{ lookup('env', 'MIARECWEB_SECRET') }}"
        python_version: "{{ lookup('env', 'MIARECWEB_PYTHON_VERSION') }}"


    - name: Update apt cache | Debian
      apt:
        update_cache: true
        cache_valid_time: 600
      changed_when: false
      when: ansible_os_family == "Debian"

    # required for miarecweb.yml - Install dependencies (requirements.txt)
    # I want to re test this, I dont ubderstand why we need system python pip
    - name: Install python-pip | CentOS
      package:
        name: python-pip
        state: present
      when: ansible_distribution == "CentOS"


  roles:
    - role: ansible-role-miarecweb
      tags:
        - miarecweb
