---
- name: Converge
  hosts: all
  become: true

  pre_tasks:

    - set_fact:
        miarecweb_version: "{{ lookup('env', 'MIARECWEB_VERSION') }}"
        miarecweb_secret: "{{ lookup('env', 'MIARECWEB_SECRET') }}"
        python_version: "{{ lookup('env', 'PYTHON_VERSION') }}"

    - name: Update apt cache | Debian
      apt:
        update_cache: true
        cache_valid_time: 600
      changed_when: false
      when: ansible_facts['os_family'] == "Debian"

  roles:
    - role: "{{ playbook_dir }}/../.." # noqa: role-name[path]
      tags:
        - miarecweb
