---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Install prerequisites
      block:
        - name: Update apt cache
          apt:
            update_cache: true
            cache_valid_time: 600
          changed_when: false
          when: ansible_os_family == "Debian"

    - set_fact:
        python_version: 3.8.16
        miarecweb_version: 8.0.0.3911
        miarecweb_secret: secret

  roles:

    # - role: miarecweb
    - role: ansible-role-miarecweb
      tags:
        - miarecweb
