---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: miarecdevops/docker-${MOLECULE_DISTRO:-ubuntu2204}-init:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  env:
    ANSIBLE_VERBOSITY: ${MOLECULE_ANSIBLE_VERBOSITY:-0}
    MIARECWEB_VERSION: ${MOLECULE_MIARECWEB_VERSION:-"2024.1.0.0"}
    MIARECWEB_SECRET: ${MOLECULE_MIARECWEB_SECRET:-"secret"}
    MIARECWEB_PYTHON_VERSION: ${MOLECULE_MIARECWEB_PYTHON_VERSION:-"3.11.7"}



verifier:
  name: testinfra
  options:
    s: true
    verbose: true
