---
# Install and Configure PostgreSQL
- name: Debian - Install PostgreSQL
  block:
    - name: Debian - Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 600
      changed_when: false
      when: ansible_os_family == "Debian"

    - name: Debian - Install PostgreSQL packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - postgresql
        - postgresql-contrib

    - name: Debian - Start PostgreSQL service
      service:
        name: postgresql
        state: started
  when: ansible_os_family == "Debian"

- name: CentOS 7 - Install PostgreSQL
  block:
    - name: CentOS 7 - Install the PostgreSQL repository
      yum:
        name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm
        state: present

    - name: CentOS 7 - Install PostgreSQL packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - postgresql12-server
        - postgresql12-contrib
      register: _postrgesql_yum_install

    - name: CentOS 7 - Inititialize the database
      shell: /usr/pgsql-12/bin/postgresql-12-setup initdb
      when: _postrgesql_yum_install.changed

    - name: CentOS 7 - Modify pg_hba.conf file
      copy:
        content: |
          # set permissions to access databases
          local all all peer
          host miarecdb miarec 127.0.0.1/32 md5
        dest: /var/lib/pgsql/12/data/pg_hba.conf

    - name: CentOS 7 - Start PostgreSQL service
      service:
        name: postgresql-12
        state: started

  when: ansible_distribution == "CentOS"

- name: Configure PostgreSQL
  block:
    - name: Install psycopg2 for ansible to be able to create postgresql users
      pip:
        name: psycopg2-binary
        state: present

    - name: Create PostgreSQL user
      postgresql_user:
        name: "miarec"
        password: "password"
        state: present
        port: 5432
      become: true
      become_user: "postgres"

    - name: Create PostgreSQL database
      postgresql_db:
        name: "miarecdb"
        owner: "miarec"
        state: present
      become: true
      become_user: "postgres"

    # This might not be needed.....
    # - name: Update user permissions for PostgreSQL User
    #   postgresql_user:
    #     name: "miarec"
    #     db: "miarecdb"
    #   become: true
    #   become_user: "postgres"

    - name: Install PostgreSQL Database Extensions
      postgresql_ext:
        name: "{{ item }}"
        db: "miarecdb"
        state: present
      become: true
      become_user: "postgres"
      with_items:
        - hstore
        - uuid-ossp
        - pg_stat_statements
