---
- name: Prepare
  hosts: all
  become: true

  pre_tasks:
    - set_fact:
        python_version: "{{ lookup('env', 'MIARECWEB_PYTHON_VERSION') }}"

  tasks:
    - include_tasks: python.yml

    # - name: Define python 3 location | Centos7
    #   when: ansible_distribution == "CentOS"
    #   block:

    #     - set_fact:
    #         compiled_python3_bin_location: "/usr/local/bin/python{{ '.'.join(python_version.split('.')[:2]) }}"

    #     - debug: var=python3_bin_location

    # - set_fact:
    #     ## Translate full python_version (3.4.5) to the MAJOR.MINOR value, like "3.4"
    #     python_version_base: "{{ '.'.join(python_version.split('.')[:2]) }}"

    # - set_fact:
    #     python_exec: "python{{ python_version_base }}"

    - include_tasks: postgresql.yml
    - include_tasks: apache.yml
