---
- name: Prepare
  hosts: all
  become: true

  pre_tasks:
    - set_fact:
        python_version: "{{ lookup('env', 'MIARECWEB_PYTHON_VERSION') }}"

  tasks:
    - include_tasks: tasks/python.yml
    - include_tasks: tasks/postgresql.yml
    - include_tasks: tasks/apache.yml
