---
- name: Prepare
  hosts: all
  become: true

  tasks:
    - name: Set python_version from environment
      set_fact:
        python_version: "{{ lookup('env', 'PYTHON_VERSION') }}"

    - include_tasks: tasks/python.yml
    - include_tasks: tasks/postgresql.yml
    - include_tasks: tasks/redis.yml
    - include_tasks: tasks/apache.yml
