---
# Install Build Dependincies for Python
- name: Python | Define build dependencies | RedHat
  set_fact:
    python_dependencies:
      - gcc
      - make
      - findutils
      - openssl-devel
      - sqlite-devel
      - bzip2-devel
      - zlib-devel
      - libffi-devel
  when: ansible_os_family == "RedHat"


- name: Python | Define build dependencies | Debian
  set_fact:
    python_dependencies:
    - gcc
    - make
    - libssl-dev
    - libsqlite3-dev
    - libbz2-dev
    - libffi-dev
    - python3-pip
  when: ansible_os_family == "Debian"

- name: Python | Install build dependencies
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ python_dependencies }}"


- name: Python | For CentOS/RedHat 7, install additional build dependencies
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == '7'
    - python_version is version('3.8', '>=')
  block:
    # SCL are required for dev-toolset-11 package
    # For RedHat Enterprise, you may need to manually add it with:
    #    yum-config-manager --enable rhel-server-rhscl-11-rpms
    - name: Python |  Install Software Collections (SCL)
      package:
        name: centos-release-scl
        state: present
      # when: ansible_distribution == "CentOS"

    # EPEL is required for openssl11 package
    - name: Python | Define EPEL package | CentOS 7
      set_fact:
        epel_package: epel-release
      when: ansible_distribution == "CentOS"

    - name: Python | Define EPEL pacakage | RHEL 7
      set_fact:
        epel_package: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      when: ansible_distribution == "RedHat"

    - name: Python | Install EPEL
      package:
        name: "{{ epel_package }}"
        state: present

    - name: Python | Install additional build dependencies | RedHat 7
      package:
        name: "{{ item }}"
        state: present
      become: true
      with_items:
        - devtoolset-11
        - openssl11-devel

    - name: Python | Get OpenSSL 1.1.1 CFLAGS | RedHat 7
      shell: pkg-config --cflags openssl11
      register: openssl11_cflags
      changed_when: false

    - name: Python | Get OpenSSL 1.1.1 LIBS | RedHat 7
      shell: pkg-config --libs openssl11
      register: openssl11_libs
      changed_when: false

    - name: Python | Prepare python compile flags | RedHat 7
      set_fact:
        python_cppflags: "{{ openssl11_cflags.stdout }}"
        python_ldflags: "{{ openssl11_libs.stdout }}"
        python_configure_command: "scl enable devtoolset-11 -- ./configure"
        python_make_command: "scl enable devtoolset-11 -- make"

- name: Python | Download source code
  get_url:
    url: "https://www.python.org/ftp/python/{{ python_version }}/Python-{{ python_version }}.tgz"
    dest: "/tmp/Python-{{ python_version }}.tgz"

- name: Python | Untar the source package
  unarchive:
    src: "/tmp/Python-{{ python_version }}.tgz"
    dest: "/tmp"
    creates: "/tmp/Python-{{ python_version }}/configure"
    copy: false


- name: Python | Run configure
  shell: "{{ python_configure_command | default('./configure') }} --enable-optimizations --enable-shared --prefix=/usr/local"
  args:
    chdir: "/tmp/Python-{{ python_version }}"
    creates: "/tmp/Python-{{ python_version }}/Makefile"
  environment:
    CPPFLAGS: "{{ python_cppflags | default('') }}"
    LDFLAGS: "{{ python_ldflags | default('') }} -Wl,-rpath=/usr/local/lib"

- name: Python | Run make
  shell: "{{ python_make_command | default('make') }}  -j{{ ansible_processor_cores }}"
  args:
    chdir: "/tmp/Python-{{ python_version }}"
    creates: "/tmp/Python-{{ python_version }}/python"


- name: Python | Run make altinstall
  command: make altinstall
  args:
    chdir: "/tmp/Python-{{ python_version }}"
  become: true